# Voxel grid parameters
grid_size: 64
voxel_size: null  # Auto-calculated as 1.0 / grid_size
gray_threshold: 0.05

# Scene bounds for voxelization (in world coordinates)
# These bounds define the 3D volume where voxels will be generated
scene_bounds:
  x_bound: [-0.5, 0.5]  # [min_x, max_x]
  y_bound: [-0.5, 0.5]  # [min_y, max_y]
  z_bound: [-0.5, 0.5]  # [min_z, max_z]

# Processing parameters (optional overrides)
batch_size: 4096  # Number of voxels to process at once
alpha_weighted: true  # Whether to weight features by alpha (density)
alpha_threshold_for_mask: 0.01  # Threshold for occupancy mask generation 