# VLM segmentation parameters
vlm:
  use_spatial_smoothing: false
  overwrite: true
  
  # VLM labeling configuration
  labeling:
    enabled: true # Enable VLM labeling pipeline
    overwrite: false  # Overwrite existing VLM labeling results
    
    # VLM segmentation step
    seg:
      num_alternative_queries: 5  # Number of alternative queries to generate
      input_num_views: 15  # Number of views to use for segmentation
      
    # VLM critic step
    critic:
      input_num_views: 10  # Number of views of the original object to show the critic`
      
    # VLM physics sampler step
    phys_sampler:
      num_sample_mat: 1 # Number of material samples to generate from the plausible range

    # VLM API and model configuration
    api:
      gemini_api_key: null  # Set to API key or leave null to use .env file
      claude_api_key: null  # Set to API key or leave null to use .env file
      gpt_api_key: null  # Set to API key or leave null to use .env file
    
    # VLM model configuration
    models:
      data_filtering: "gemini-2.5-pro-preview-03-25"  # Model for data filtering
      segmentation: "gemini-2.0-flash"  # Model for segmentation
      seg_critic: "gemini-2.5-pro-preview-03-25"  # Model for segmentation critic
      phys_sampler: "gemini-1.5-flash-latest"  # Model for physics sampler
      phys_judge: "gemini-2.0-flash"  # Model for physics judging
      parse_critic: "gemini-2.0-flash"  # Model for parse critic
    
# Neural segmentation parameters
neural:
  result_id: null
  feature_type: "clip"
  cache_results: false

# Material dictionary
material_dict_path: null  # Optional: Path to material dictionary JSON file 